<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SHREEYA-MALHAR" name="Default test" tests="2" failures="1" timestamp="9 Nov 2017 18:06:23 GMT" time="40.454" errors="0">
  <testcase name="feature" time="39.57" classname="CucumberPackage.Cucumber.RunnerClass">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: expected [http://opensource.demo.orangehrmlive.com/index.php/dashboard] but found [http://opensource.demo.orangehrmlive.com/index.php/auth/validateCredentials]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [http://opensource.demo.orangehrmlive.com/index.php/dashboard] but found [http://opensource.demo.orangehrmlive.com/index.php/auth/validateCredentials]
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: expected [http://opensource.demo.orangehrmlive.com/index.php/dashboard] but found [http://opensource.demo.orangehrmlive.com/index.php/auth/validateCredentials]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at CucumberPackage.Cucumber.Cucumber.i_should_get_logged_in_by_clicking_on_the_Login_button(Cucumber.java:48)
	at âœ½.Then I should get logged in by clicking on the Login button(Selenium.feature:9)
]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase name="f" time="0.002" classname="CucumberPackage.Cucumber.RunnerClass"/>
</testsuite> <!-- Default test -->
